name: anime_red
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  objectbox: ^2.4.0
  objectbox_generator: ^2.4.0
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  injectable: ^1.5.3
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  lottie: ^3.0.0
  readmore: ^2.2.0
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/

  fonts:
    - family: Comic Neue
      fonts:
        - asset: assets/fonts/ComicNeue-Light.ttf
        - weight: 300
        - asset: assets/fonts/ComicNeue-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ComicNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/ComicNeue-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/ComicNeue-BoldItalic.ttf
          weight: 700
          style: italic
