class AnimeGenres {
  static const Map<String, String> _genreList = {
    "Action": "action",
    "Adventure": "adventure",
    "Cars": "cars",
    "Comedy": "comedy",
    "Crime": "crime",
    "Dementia": "dementia",
    "Demons": "demons",
    "Drama": "drama",
    "Dub": "dub",
    "Ecchi": "ecchi",
    "Family": "family",
    "Fantasy": "fantasy",
    "Game": "game",
    "Gourmet": "gourmet",
    "Harem": "harem",
    "Historical": "historical",
    "Horron": "horror",
    "Josei": "josei",
    "Kids": "kids",
    "Magic": "magic",
    "Martial Arts": "martial-arts",
    "Mecha": "mecha",
    "Military": "military",
    "Music": "music",
    "Mystery": "mystery",
    "Parody": "parody",
    "Police": "police",
    "Psychological": "psychological",
    "Romance": "romance",
    "Samurai": "samurai",
    "School": "school",
    "Sci Fi": "sci-fi",
    "Seinen": "seinen",
    "Shoujo": "shoujo",
    "Shoujo Ai": "shoujo-ai",
    "Shounen": "shounen",
    "Shounen Ai": "shounen-ai",
    "Slice of Life": "slice-of-Life",
    "Space": "space",
    "Sports": "sports",
    "Super Power": "super-power",
    "Supernatural": "supernatural",
    "Suspense": "suspense",
    "Thriller": "thriller",
    "Vampire": "vampire",
    "Yaoi": "yaoi",
    "Yuri": "yuri",
  };

  /// Key will be the display name and Value is query name
  static Map<String, String> getGenreList() => _genreList;
}
